// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRPS.Entities;

#nullable disable

namespace SRPS.Entities.Migrations
{
    [DbContext(typeof(SRPSDbContext))]
    [Migration("20240109081216_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SRPS.Entities.DomainModels.StudentsDomainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFeesPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("Marks")
                        .HasColumnType("int");

                    b.Property<string>("MothersName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SchoolHouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SRPS_TBL_Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3f6452d-b736-4d05-8390-79048e69c3cc"),
                            Class = "XI",
                            FathersName = "Ram Kumar",
                            IsFeesPaid = false,
                            Marks = 80,
                            MothersName = "Shoobha Devi",
                            SchoolHouse = "Challenger",
                            StudentName = "Rohit Kumar"
                        },
                        new
                        {
                            Id = new Guid("a7b4f091-8c66-4a0b-9e86-02b8c1f64c5e"),
                            Class = "XII",
                            FathersName = "Raj Shukla",
                            IsFeesPaid = false,
                            Marks = 90,
                            MothersName = "Gayatri Shukla",
                            SchoolHouse = "Challenger",
                            StudentName = "Rahul Shukla"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
